### ISSUE TITLE
Grader ?

### ISSUE THREAD

**Issue by PalmPTSJ** [op01/ComO-Reference#3]
เราควรจะมี grader มะ เผื่อทำในคาบ + การบ้าน
ใช้ monograder ก็ได้ หรือกุคิดได้อีกแบบ

เอาไว้ใน yzi.me ไปเลย แล้วใช้วิธีตรวจแบบ Code Jam
ถ้าคนไม่รู้วิธี redirect ก็อาจจะแบบ ทำโปรแกรมขึ้นมาเลย ให้ต่อไปที่ grader แล้วจัดการให้หมด คนใช้แค่เลือก code แล้วโปรแกรมเราจะ run ให้ ส่งไปตรวจให้ แล้วแสดงผลมา

**Comment by op01** [comment]
อืม เชิญท่านประธานเปิดโดเมนเลยใช้ account เดิมนะ
แล้วก็ควรจะทำแบบเป็น user ดีป่าว หรือไม่ต้อง login ตรวจให้รู้ว่าถูกก็พอ

**Comment by PalmPTSJ** [comment]
account เดิมลืม user/pass ไปละ 555
ก็ถ้าทำเป็น user ได้ก็ดี เผื่อจะสั่งการบ้านไรงี้ และเก็บโค้ดไว้ตรวจด้วย
(ถ้าว่าง ทำเป็นแบบให้ message กันได้ไปเลย เผื่อใครสงสัยโจทย์ข้อไหนก็ถามมาได้ ทั้งสมาชิกชุมนุมใหม่ และพวกที่ advanced แล้วไรงี้)
